### ISSUE TITLE
Run code

### ISSUE THREAD

**Issue by kiwiyou** [evalsa/worker#1]
- [x] compile main source file - #2 
- [x] use nsjail to chroot tmpfs and launch executable - #3 
- [x] pipe executable stdout, stdin, and stderr as binary -#3
